"""token_transaction

Revision ID: 25bc6deef10f
Revises: 2c65442e60fc
Create Date: 2025-03-16 17:24:49.938029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bc6deef10f'
down_revision: Union[str, None] = '2c65442e60fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_transactions', 'stars_amount')
    op.add_column('transactions', sa.Column('stars_amount', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'stars_amount')
    op.add_column('token_transactions', sa.Column('stars_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
